### ISSUE TITLE
[Bug]: The 'MissClick?' Time picker is not null safe

### ISSUE THREAD

**Issue by aryanmishra29** [maityamit/Sleepometer-Android-App#57]
### Contact Details

aryan29mishra@gmail.com

### What happened?

When we click on the MissClick? button for the first time and click save without setting any time, then the app crashes.
We need to make it null safe by doing a few changes to the java code.

<img width="364" alt="Screenshot 2023-02-03 at 12 39 21 PM" src="https://user-images.githubusercontent.com/92439461/216535014-25bee2a4-bb8f-4e3f-ad00-61c4a03e2eb2.png">

### Relevant log output

```shell
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.TimePicker.getHour()' on a null object reference
        at sleepometerbyamitmaity.example.sleepometer.fragments.HomeFragment$7.onClick(HomeFragment.java:223)
        at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aryanmishra29** [comment]
@maityamit Kindly review the issue, and assign it to me under IWOC label.
I will make the time picker null safe using some checks and conditions.

**Comment by maityamit** [comment]
@aryanmishra29 start :)

**Comment by maityamit** [comment]
@aryanmishra29 any update ?

**Comment by aryanmishra29** [comment]
Just now made a PR, Kindly review it!
